{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d8302751-c078-45c5-bf07-b3d4adc5c5c2",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import glob\n",
    "import uuid\n",
    "import warnings\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from datetime import datetime\n",
    "\n",
    "# Prevent terminal flooding\n",
    "warnings.filterwarnings(\"ignore\")\n",
    "\n",
    "def run_entire_pipeline():\n",
    "    \"\"\"\n",
    "    Automatically aggregates all CSV files from the 'data/' folder, \n",
    "    calculates metrics, triggers performance engine, updates the dashboard database,\n",
    "    and returns a clean master dataframe.\n",
    "    \"\"\"\n",
    "    DATA_FOLDER = \"data\"\n",
    "    OUTPUT_FOLDER = \"output\"\n",
    "    \n",
    "    # Ensure standard structural directories exist\n",
    "    os.makedirs(DATA_FOLDER, exist_ok=True)\n",
    "    os.makedirs(OUTPUT_FOLDER, exist_ok=True)\n",
    "    os.makedirs(os.path.join(OUTPUT_FOLDER, \"grade_cards\"), exist_ok=True)\n",
    "    os.makedirs(os.path.join(OUTPUT_FOLDER, \"reports\"), exist_ok=True)\n",
    "\n",
    "    csv_files = sorted(glob.glob(os.path.join(DATA_FOLDER, \"*.csv\")))\n",
    "    if not csv_files:\n",
    "        return None, \"Data folder completely empty. Please drop or upload a CSV file.\"\n",
    "\n",
    "    try:\n",
    "        # Load & Clean Dataframes\n",
    "        quiz_data = [pd.read_csv(file) for file in csv_files]\n",
    "        clean_quiz = []\n",
    "        for df in quiz_data:\n",
    "            df.columns = df.columns.str.strip()\n",
    "            if \"Email\" in df.columns:\n",
    "                df[\"Email\"] = df[\"Email\"].astype(str).str.lower().str.strip()\n",
    "            if \"Name\" in df.columns:\n",
    "                df[\"Name\"] = df[\"Name\"].astype(str).str.strip()\n",
    "            clean_quiz.append(df)\n",
    "\n",
    "        # Dynamic Extraction & Score Merges\n",
    "        master_df = None\n",
    "        for day_no, df in enumerate(clean_quiz, start=1):\n",
    "            temp = df.copy()\n",
    "            score_column = None\n",
    "            for col in [\"Total score\", \"Score\", \"Marks\", \"Result\"]:\n",
    "                if col in temp.columns:\n",
    "                    score_column = col\n",
    "                    break\n",
    "\n",
    "            if score_column is None:\n",
    "                continue\n",
    "\n",
    "            score = temp[score_column].astype(str).str.split(\"/\", expand=True)\n",
    "            temp[f\"Day{day_no}\"] = score[0].str.strip().astype(float)\n",
    "            temp[f\"Day{day_no}_Max\"] = score[1].str.strip().astype(float)\n",
    "\n",
    "            keep_columns = [\"Name\", \"Email\", f\"Day{day_no}\", f\"Day{day_no}_Max\"]\n",
    "            temp = temp[[c for c in keep_columns if c in temp.columns]]\n",
    "\n",
    "            if master_df is None:\n",
    "                master_df = temp\n",
    "            else:\n",
    "                if \"Name\" in temp.columns:\n",
    "                    temp = temp.drop(columns=[\"Name\"])\n",
    "                master_df = master_df.merge(temp, on=\"Email\", how=\"outer\")\n",
    "\n",
    "        # Restore Student Names via Lookup Mapping\n",
    "        name_lookup = {}\n",
    "        for df in clean_quiz:\n",
    "            if \"Email\" in df.columns and \"Name\" in df.columns:\n",
    "                for _, row in df.iterrows():\n",
    "                    email = str(row[\"Email\"]).strip().lower()\n",
    "                    if email not in name_lookup and str(row[\"Name\"]) != \"nan\":\n",
    "                        name_lookup[email] = str(row[\"Name\"]).strip()\n",
    "        \n",
    "        master_df[\"Name\"] = master_df[\"Email\"].map(name_lookup)\n",
    "        \n",
    "        # Performance Engine Core Parsing\n",
    "        score_cols = sorted([c for c in master_df.columns if c.startswith(\"Day\") and not c.endswith(\"_Max\")])\n",
    "        max_cols = sorted([c for c in master_df.columns if c.endswith(\"_Max\")])\n",
    "\n",
    "        master_df[\"Attempted_Quiz\"] = (master_df[score_cols] > 0).sum(axis=1)\n",
    "        master_df[\"Attendance\"] = master_df[\"Attempted_Quiz\"].fillna(0).astype(float)\n",
    "        \n",
    "        TOTAL_QUIZZES = len(score_cols) if len(score_cols) > 0 else 1\n",
    "        master_df[\"Attendance_%\"] = ((master_df[\"Attempted_Quiz\"] / TOTAL_QUIZZES) * 100).round(2)\n",
    "        master_df[\"Total_Obtained\"] = master_df[score_cols].sum(axis=1)\n",
    "\n",
    "        master_df[\"Total_Maximum\"] = 0\n",
    "        for score_col, max_col in zip(score_cols, max_cols):\n",
    "            master_df[\"Total_Maximum\"] += np.where(master_df[score_col] > 0, master_df[max_col], 0)\n",
    "\n",
    "        master_df[\"Percentage\"] = np.where(\n",
    "            master_df[\"Total_Maximum\"] == 0, 0,\n",
    "            ((master_df[\"Total_Obtained\"] / master_df[\"Total_Maximum\"]) * 100)\n",
    "        ).round(2)\n",
    "\n",
    "        COURSE_TOTAL_MAX = master_df[max_cols].max().sum()\n",
    "        if COURSE_TOTAL_MAX == 0: COURSE_TOTAL_MAX = 1\n",
    "        \n",
    "        master_df[\"Quiz_Percentage\"] = master_df[\"Percentage\"]\n",
    "        master_df[\"Overall_Percentage\"] = ((master_df[\"Total_Obtained\"] / COURSE_TOTAL_MAX) * 100).round(2)\n",
    "        master_df[\"Attendance_Ratio\"] = (master_df[\"Attempted_Quiz\"] / TOTAL_QUIZZES)\n",
    "        master_df[\"Performance_Score\"] = (master_df[\"Quiz_Percentage\"] * master_df[\"Attendance_Ratio\"]).round(2)\n",
    "\n",
    "        # Rank, Grade, Percentile Logic\n",
    "        master_df[\"Rank\"] = master_df[\"Overall_Percentage\"].rank(ascending=False, method=\"dense\").astype(int)\n",
    "        master_df[\"Percentile\"] = (master_df[\"Overall_Percentage\"].rank(pct=True) * 100).round(2)\n",
    "\n",
    "        def assign_grade(overall_percentage):\n",
    "            if overall_percentage >= 90: return \"A+\"\n",
    "            elif overall_percentage >= 80: return \"A\"\n",
    "            elif overall_percentage >= 70: return \"B+\"\n",
    "            elif overall_percentage >= 60: return \"B\"\n",
    "            elif overall_percentage >= 50: return \"C\"\n",
    "            elif overall_percentage >= 40: return \"D\"\n",
    "            else: return \"F\"\n",
    "\n",
    "        master_df[\"Grade\"] = master_df[\"Overall_Percentage\"].apply(assign_grade)\n",
    "\n",
    "        # AI Insights Auto Engine\n",
    "        def generate_ai_insight(row):\n",
    "            qp, op, att, attempt = row[\"Quiz_Percentage\"], row[\"Overall_Percentage\"], row[\"Attendance_%\"], row[\"Attempted_Quiz\"]\n",
    "            insights = []\n",
    "            if att >= 85: insights.append(\"Excellent attendance throughout the course.\")\n",
    "            elif att >= 60: insights.append(\"Good attendance. Try attending every quiz.\")\n",
    "            elif att >= 30: insights.append(\"Low participation. Attend more quizzes for better performance.\")\n",
    "            else: insights.append(\"Very low participation. Course performance is affected.\")\n",
    "\n",
    "            if qp >= 90: insights.append(\"Outstanding performance in attempted quizzes.\")\n",
    "            elif qp >= 75: insights.append(\"Strong academic performance.\")\n",
    "            elif qp >= 60: insights.append(\"Average performance with scope for improvement.\")\n",
    "            elif qp >= 40: insights.append(\"Below average performance.\")\n",
    "            else: insights.append(\"Needs significant academic improvement.\")\n",
    "\n",
    "            if op >= 85: insights.append(\"Consistently performing well across the course.\")\n",
    "            elif op >= 60: insights.append(\"Maintaining satisfactory overall progress.\")\n",
    "            elif op >= 40: insights.append(\"Overall progress is moderate.\")\n",
    "            else: insights.append(\"Overall course performance is currently low.\")\n",
    "\n",
    "            if attempt == 1: insights.append(\"Only one quiz attempted. More participation is recommended.\")\n",
    "            elif attempt >= 6: insights.append(\"Highly consistent participation across quizzes.\")\n",
    "            return \" \".join(insights)\n",
    "\n",
    "        master_df[\"Insight\"] = master_df.apply(generate_ai_insight, axis=1)\n",
    "\n",
    "        # Final Re-ordering & Export to CSV for Dashboard\n",
    "        col_order = [\"Name\", \"Email\"] + [c for c in master_df.columns if c not in [\"Name\", \"Email\"]]\n",
    "        master_df = master_df[col_order].sort_values(by=\"Rank\")\n",
    "        master_df.to_csv(os.path.join(OUTPUT_FOLDER, \"master_df.csv\"), index=False)\n",
    "        \n",
    "        return master_df, \"✅ Entire Analytics Pipeline Processed Successfully!\"\n",
    "    except Exception as e:\n",
    "        return None, f\"❌ Pipeline Broken: {str(e)}\""
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:myjupyter]",
   "language": "python",
   "name": "conda-env-myjupyter-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
